### PR TITLE
Unit tests , add new and refactor

### PR DESCRIPTION
**Pull request by potapovDim**

### CODE REVIEW

**Comment by alexeybondarenko** [comment]
Hi, @potapovDim)

I'm so confused that you are contributing in this repo) Do you use this components in your projects?

If you need some help to integrate them to webpack build I can send a link to An example

**Comment by potapovDim** [comment]
@alexeybondarenko hello , i like open source projects, so i decide to do tests for this project , if you oppose , i will not

**Comment by alexeybondarenko** [comment]
@potapovDim, I'm not against sure. it is open source project. Thank you for tests!

I will fix Travis build soon for this repo. So the tests will run every commit.

**Comment by potapovDim** [comment]
@alexeybondarenko i don`t understand, why in some components you use jsx and in some components you use React.Create... ?

**Comment by alexeybondarenko** [comment]
@potapovDim usually, it's a legacy. In Icon component when it was created we had added property `tag`. Now React.createElement is meaningless. Thank for this refactor.

**Pull request merged**
